{
 "title": "Agente de monitoramento web 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latência média RTT Google",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT timestamp, rtt_avg, target, packet_loss\nFROM ping_results\nWHERE target = 'google.com'\nORDER BY timestamp ASC;\n",
     "rawQueryText": "SELECT timestamp, rtt_avg, target, packet_loss\nFROM ping_results\nWHERE target = 'google.com'\nORDER BY timestamp ASC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tempo de Carregamento de google.com",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "load" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, load_time\nFROM web_test_results\nWHERE url = 'https://google.com'\nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT timestamp, load_time\nFROM web_test_results\nWHERE url = 'https://google.com'\nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Código de retorno google.com",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, status_code\nFROM web_test_results\nWHERE url = 'https://google.com'\nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT timestamp, status_code\nFROM web_test_results\nWHERE url = 'https://google.com'\nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latência média RTT Youtube",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT timestamp, rtt_avg, target, packet_loss\nFROM ping_results\nWHERE target = 'youtube.com'\nORDER BY timestamp ASC;\n",
     "rawQueryText": "SELECT timestamp, rtt_avg, target, packet_loss\nFROM ping_results\nWHERE target = 'youtube.com'\nORDER BY timestamp ASC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tempo de Carregamento de Youtube",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "load" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, load_time\nFROM web_test_results\nWHERE url = 'https://youtube.com'\nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT timestamp, load_time\nFROM web_test_results\nWHERE url = 'https://youtube.com'\nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Código de retorno Youtube",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, status_code\nFROM web_test_results\nWHERE url = 'https://youtube.com'\nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT timestamp, status_code\nFROM web_test_results\nWHERE url = 'https://youtube.com'\nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latência média RTT RNP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT timestamp, rtt_avg, target, packet_loss\nFROM ping_results\nWHERE target = 'rnp.br'\nORDER BY timestamp ASC;\n",
     "rawQueryText": "SELECT timestamp, rtt_avg, target, packet_loss\nFROM ping_results\nWHERE target = 'rnp.br'\nORDER BY timestamp ASC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tempo de Carregamento RNP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "load" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, load_time\nFROM web_test_results\nWHERE url = 'https://rnp.br'\nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT timestamp, load_time\nFROM web_test_results\nWHERE url = 'https://rnp.br'\nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Código de retorno RNP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp, status_code\nFROM web_test_results\nWHERE url = 'https://rnp.br'\nORDER BY timestamp ASC\n",
     "rawQueryText": "SELECT timestamp, status_code\nFROM web_test_results\nWHERE url = 'https://rnp.br'\nORDER BY timestamp ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}